// Mock organizations data for development
export const mockOrganizations = [
  {
    id: 'mock-org-1',
    name: 'Demo Company',
    plan: 'free' as const,
    owner_id: 'mock-user-1',
    created_at: '2024-01-15T10:30:00Z',
    conversations_this_month: 45,
    ai_responses_used: 23,
    stripe_customer_id: 'cus_mock_1',
    stripe_subscription_id: null,
    billing_cycle_start: '2024-03-01T00:00:00Z',
    widget_key: 'demo-widget-key-123',
    settings: {
      primaryColor: '#0066FF',
      position: 'bottom-right' as const,
      welcomeMessage: 'Hello! How can I help you today?',
      offlineMessage: 'Sorry, we are currently offline. Please leave a message.',
      avatar: null,
      showBranding: true,
      bubbleIcon: 'chat' as const,
      bubbleSize: 'medium' as const,
      bubbleStyle: 'solid' as const,
      bubbleShadow: true,
      bubbleAnimation: 'none' as const
    }
  },
  {
    id: 'mock-org-2',
    name: 'Tech Startup Inc',
    plan: 'pro' as const,
    owner_id: 'mock-user-2',
    created_at: '2024-02-20T14:15:00Z',
    conversations_this_month: 128,
    ai_responses_used: 89,
    stripe_customer_id: 'cus_mock_2',
    stripe_subscription_id: 'sub_mock_2',
    billing_cycle_start: '2024-03-01T00:00:00Z',
    widget_key: 'tech-widget-key-456',
    settings: {
      primaryColor: '#FF6B35',
      position: 'bottom-left' as const,
      welcomeMessage: 'Welcome to Tech Startup! How can we assist you?',
      offlineMessage: 'Our team is offline right now. We\'ll respond soon.',
      avatar: null,
      showBranding: false,
      bubbleIcon: 'message-circle' as const,
      bubbleSize: 'large' as const,
      bubbleStyle: 'gradient' as const,
      bubbleShadow: true,
      bubbleAnimation: 'pulse' as const
    }
  },
  {
    id: 'mock-org-3',
    name: 'Enterprise Corp',
    plan: 'enterprise' as const,
    owner_id: 'mock-user-3',
    created_at: '2023-12-10T09:00:00Z',
    conversations_this_month: 342,
    ai_responses_used: 267,
    stripe_customer_id: 'cus_mock_3',
    stripe_subscription_id: 'sub_mock_3',
    billing_cycle_start: '2024-03-01T00:00:00Z',
    widget_key: 'enterprise-widget-key-789',
    settings: {
      primaryColor: '#10B981',
      position: 'bottom-right' as const,
      welcomeMessage: 'Thank you for contacting Enterprise Corp. How may we help?',
      offlineMessage: 'Our support team is available 24/7. Please leave a message.',
      avatar: null,
      showBranding: false,
      bubbleIcon: 'headphones' as const,
      bubbleSize: 'large' as const,
      bubbleStyle: 'solid' as const,
      bubbleShadow: true,
      bubbleAnimation: 'bounce' as const
    }
  },
  {
    id: 'mock-org-4',
    name: 'Local Business',
    plan: 'free' as const,
    owner_id: 'mock-user-4',
    created_at: '2024-03-01T16:45:00Z',
    conversations_this_month: 12,
    ai_responses_used: 5,
    stripe_customer_id: null,
    stripe_subscription_id: null,
    billing_cycle_start: '2024-03-01T00:00:00Z',
    widget_key: 'local-widget-key-012',
    settings: {
      primaryColor: '#8B5CF6',
      position: 'bottom-right' as const,
      welcomeMessage: 'Hi there! Welcome to our store.',
      offlineMessage: 'We\'re currently closed. Please send us a message!',
      avatar: null,
      showBranding: true,
      bubbleIcon: 'chat' as const,
      bubbleSize: 'medium' as const,
      bubbleStyle: 'solid' as const,
      bubbleShadow: false,
      bubbleAnimation: 'none' as const
    }
  },
  {
    id: 'mock-org-5',
    name: 'Creative Agency',
    plan: 'pro' as const,
    owner_id: 'mock-user-5',
    created_at: '2024-01-28T11:20:00Z',
    conversations_this_month: 89,
    ai_responses_used: 67,
    stripe_customer_id: 'cus_mock_5',
    stripe_subscription_id: 'sub_mock_5',
    billing_cycle_start: '2024-03-01T00:00:00Z',
    widget_key: 'creative-widget-key-345',
    settings: {
      primaryColor: '#F59E0B',
      position: 'bottom-left' as const,
      welcomeMessage: 'Hello! We\'re excited to hear from you.',
      offlineMessage: 'Our creative team will get back to you soon!',
      avatar: null,
      showBranding: true,
      bubbleIcon: 'sparkles' as const,
      bubbleSize: 'medium' as const,
      bubbleStyle: 'gradient' as const,
      bubbleShadow: true,
      bubbleAnimation: 'pulse' as const
    }
  }
]
